### ISSUE TITLE
Failing tests on v0.4+

### ISSUE THREAD

**Issue by kbarbary** [JuliaAstro/ERFA.jl#12]
```
$ julia test/runtests.jl 
ERROR: LoadError: ccall: could not find function eraAb in library /usr/lib/x86_64-linux-gnu/liberfa.so.1
```

It would be good to get tests passing on Julia v0.4+ and tag a new version, if anyone wants to take responsibility for this package.

**Comment by nirinA** [comment]
is tagging a new version will be sufficient for the tests to pass? or is there something else to be fixed?
last time i've tried with v0.5 -Version 0.5.0-dev+989 (2015-10-26 18:47 UTC), Pkg.add("ERFA") installed liberfa version 1.1.1
i'll give a look at the package this week-end.

**Comment by kbarbary** [comment]
Sorry, I should have said that this is on master. I have a system liberfa installed for some reason, which is only v1.0.0. So that might be the only problem here. It would be nice to be able to *make* BinDeps install the private version, so we can guarantee we get v1.2.0 (if it's really needed).

**Comment by nirinA** [comment]
are there some rules for version numbering?
i'll try to tag a new version with:
```
Pkg.tag("ERFA",:minor)
```

**Comment by kbarbary** [comment]
I usually increment `:minor` only when adding new features. See [semantic versioning](http://semver.org) for more.

Should probably review and merge #13 and #14 before tagging though.

**Comment by kbarbary** [comment]
Probably should also change `julia 0.2` -> `julia 0.3` in REQUIRE.

**Comment by nirinA** [comment]
i tried to tag a new version, but i was not able to publish it and submit the pull request. i get permission denied error.
so, someone else may try to tag this new version.

**Comment by kbarbary** [comment]
Have you forked JuliaLang/METADATA.jl on github? There are no special permissions needed to submit a PR.

Personally, I usually use `Pkg.tag()` to create the tag & metadata entry, but then manually push using command-line `git` and the GitHub interface. `Pkg.submit/publish` are just a bit too opaque for me.

Should tag latest master; Julia 0.3 is broken on the commit you tagged v0.1.1 (see #16). Probably safest/easiest to just create a new `v0.1.2` tag.

**Comment by nirinA** [comment]
yes, i have forked METADATA.jl. but still no luck, it appears i can't push from my local METADATA.jl repository to my github fork of METADATA.jl. i don't see why i cannot push for now.

**Comment by kbarbary** [comment]
I'll go ahead and tag v0.1.2 for now.

**Comment by kbarbary** [comment]
Ended up tagging as v0.1.1, as `Pkg.tag` wouldn't let me skip v0.1.1. I've moved the git tag in the repo.
