### ISSUE TITLE
Building on Windows?

### ISSUE THREAD

**Issue by crbinz** [JuliaAstro/ERFA.jl#17]
Has anyone successfully built this on a Windows machine? If not, what's required to be able to do this?

```
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32
julia> Pkg.add("ERFA")
INFO: Cloning cache of ERFA from git://github.com/JuliaAstro/ERFA.jl.git
INFO: Installing ERFA v0.1.1
INFO: Building ERFA
================================[ ERROR: ERFA ]=================================

LoadError: None of the selected providers can install dependency liberfa.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\cbinz\.julia\v0.4\ERFA\deps\build.jl, in expression starting on line 19

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: ERFA had build errors.

 - packages with build errors remain installed in C:\Users\cbinz\.julia\v0.4
 - build the package(s) and all dependencies with `Pkg.build("ERFA")`
 - build a single package by running its `deps/build.jl` script

================================================================================
```

Thanks,
Chris

**Comment by kbarbary** [comment]
My WIndows knowledge is extremely limited, but my understanding is that you'll need to have a UNIX-compatible environment within Windows, such as mingw with msys2 or cygwin. (The build process for ERFA uses autotools, so you need to be able to run things like `./configure` and `make`.)

Ideally, Windows binaries for liberfa would be built and distributed. Then we could just use those, like we do for cfitsio on Windows. Maybe I'll ping the liberfa folks about it.

**Comment by crbinz** [comment]
I was able to build liberfa using Cygwin without too much trouble, but I still get the same build errors for this package. I agree that binaries would make this much easier. In the mean time, is there a way to point ERFA.jl to the library location somehow? Or somewhere I should move the library?

**Comment by kbarbary** [comment]
I *think* that if you put the dll somewhere the loader can find it, `Pkg.build("ERFA")` should succeed. On linux, you'd set the `LD_LIBRARY_PATH` environment variable to include the directory containing the DLL.

**Comment by crbinz** [comment]
The question is where to put it, then. I tried looking at the BinDeps documentation but I really have no idea here.

**Comment by kbarbary** [comment]
Try master now. I uploaded windows binaries and updated the build script to use them.

**Comment by crbinz** [comment]
Works great, thank you.

**Comment by kbarbary** [comment]
Great!
