### ISSUE TITLE
@test isapprox doesn't fail as expected

### ISSUE THREAD

**Issue by nirinA** [JuliaAstro/ERFA.jl#31]
some constants have their values changed in the last SOFA release, and will be updated with the future liberfa release:

https://github.com/nirinA/ERFA.jl/blob/IAU2012/src/erfa_common.jl

running the current `runtests.jl`, it doesn't fail as it should do. for instance:
```
julia> @test_approx_eq_eps(4.289638913597693e-5, 4.28963889781338e-5,  1.0e-16)
WARNING: @test_approx_eq_eps is deprecated, use `@test 4.289638913597693e-5 ≈ 4.28963889781338e-5 atol=1.0e-16` instead
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] @test_approx_eq_eps(::ANY, ::ANY, ::ANY) at ./deprecated.jl:1031
 [3] eval(::Module, ::Any) at ./boot.jl:235
 [4] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [5] macro expansion at ./REPL.jl:97 [inlined]
 [6] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
ERROR: assertion failed: |4.289638913597693e-5 - 4.28963889781338e-5| <= 1.0e-16
  4.289638913597693e-5 = 4.289638913597693e-5
  4.28963889781338e-5 = 4.28963889781338e-5
  difference = 1.578431328241696e-13 > 1.0e-16
```
whereas:
```
julia> @test isapprox(4.289638913597693e-5, 4.28963889781338e-5, atol=1e-16)
Test Passed
```

**Comment by giordano** [comment]
`isapprox` tests the following:
```julia
abs(x-y) <= atol + rtol*max(abs(x), abs(y)))
```
Does setting `rtol` to `0` help?

**Comment by nirinA** [comment]
yes, that needs this `rtol=0` keyword argument. i would like it to be more verbose as `@test_approx_eq_eps` though.

**Comment by giordano** [comment]
An alternative is to set only `rtol = 1e-8`, without touching `atol`.

**Comment by nirinA** [comment]
hmm, i'll stick with comparing the difference and `atol`. i'm confused with other value of `rtol`! need to see this more in detail.
thanks for the tips anyway.

**Comment by giordano** [comment]
The new syntax for `isapprox` proposed in https://github.com/JuliaLang/julia/pull/22742 should do what you want: with `atol > 0` there will be no need to explicitly set `rtol=0`
