### ISSUE TITLE
Remove the `era` prefix and use standard Julia function naming rules

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/ERFA.jl#34]
Due to Julia having proper namespaces, the `era` prefixes and resulting non-conforming camel-case function names are not necessary.

This could be done during the incoming Julia 1.0 overhaul. Thoughts?

**Comment by giordano** [comment]
I think it might be a good idea, however having the function name in the package  matching the function called from the C library is useful to programmatically define the functions. To be honest, it's not hard to concatenate "erfa" with the function name, so my objection isn't that strong after all.

**Comment by giordano** [comment]
I just realized that all functions are exported.  Do you plan to unexport them?

**Comment by helgee** [comment]
I am undecided about this. On the hand ERFA dumps quite a load of very specialized functions into the namespace on the other hand they are (mostly) part of the public API.

**Comment by giordano** [comment]
I think it would make sense to remove the "era" prefix if the functions weren't exported, and the use "ERFA." prefix instead.  Otherwise I don't get your comment about proper namespaces in Julia.

**Comment by kbarbary** [comment]
If we're breaking backwards compatibility anyway, we can just remove all `era_` prefixes and also remove all exports (with a deprecation cycle). `ERFA.foo()` is not much longer than `era_foo()`.

**Comment by helgee** [comment]
@giordano: My comment was aiming at the fact that if you import a C header you will have no choice but to get all symbols it defines. Thus a prefix is the only way to avoid namespace pollution. In Julia you have a choice.

I think this is one the remaining areas where there is no clear established practice, yet. See e.g. https://discourse.julialang.org/t/is-an-explicit-export-a-good-thing/7446, https://github.com/JuliaLang/julia/issues/17948
I am squarely in the "If it's exported, it's part of the public API" camp of the discussion and would argue to the leave the exports in place and let the user decide.

**Comment by giordano** [comment]
> @giordano: My comment was aiming at the fact that if you import a C header you will have no choice but to get all symbols it defines. Thus a prefix is the only way to avoid namespace pollution. In Julia you have a choice.

I understand this, but I miss what's the difference for the user between a C library with no prefix and a Julia package that exports all functions.  The difference is that in case of name clashing between functions exported to the main scope you can still identify the function with the module's name?

> I am squarely in the "If it's exported, it's part of the public API" camp

I think I'm in the "if it's documented, it's part of the public API" camp (I don't know if this was suggested in that thread, didn't read).  Ok, "ERFA" isn't a good example in this regard, as there is no documentation 😄  However, I don't want to push my view on you.

**Comment by helgee** [comment]
> I understand this, but I miss what's the difference for the user between a C library with no prefix and a Julia package that exports all functions. The difference is that in case of name clashing between functions exported to the main scope you can still identify the function with the module's name?

Yes.

Based on this discussion and the new 0.7 `import`/`using` semantics I would define my personal preference as follows:

* **There is no name clash:** Import only the (exported) things I need, e.g. `using ERFA: foo`
* **There is a name clash or I need to extend a function:** Import only the module and use the fully-qualified name, e.g. `import ERFA; ERFA.foo()`

> I think I'm in the "if it's documented, it's part of the public API" camp (I don't know if this was suggested in that thread, didn't read).

What I dislike about this approach is that it keeps me from adding docstrings to private functions for myself. [Future Helge](https://www.youtube.com/watch?v=jQvvmT3ab80) appreciates those 😂

**Comment by giordano** [comment]
> What I dislike about this approach is that it keeps me from adding docstrings to private functions for myself

Don't add them to the documentation 😃

**Comment by helgee** [comment]
Yes, but then I cannot discern from looking at code whether something is public or private. Which is not a tragedy but I want my cake and also eat it 😂 😂

**Comment by helgee** [comment]
The only thing that is really missing in my book is syntax for aliases https://github.com/JuliaLang/julia/issues/1255. Something like:
```julia
using ERFA: foo => bar
```

**Comment by giordano** [comment]
At this point I don't have a strong opinion about whether unexporting the functions, probably just a slight preference for doing so

**Comment by giordano** [comment]
Anyway, I'm really looking forward to `AstronomicalTime.jl` for a more human-friendly user interface to this stuff 😃

**Comment by giordano** [comment]
Closed by #35
