### ISSUE TITLE
All matrices returned by ERFA need to be transposed

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/ERFA.jl#44]
Column-major vs. row-major and all that 🙈

See e.g. here: https://github.com/JuliaAstro/ERFA.jl/blob/master/src/n.jl#L42

That function should return `permutedims(rmatn)`.

**Comment by helgee** [comment]
Sorry about that 😬 It might be time to tag 1.0 so that it’s more obvious when there are breaking changes.

My impression that nobody uses the library was obviously false. Out of curiosity, which functions are you using @crbinz?

**Comment by crbinz** [comment]
We have an internal package for reference frames. 

```julia
DAS2R
eqeq94
sp00
pom00
gst94
obl80
nut80
nutmat
pmat76
dtf2d
utctai
taitt
utcut1
tttai
tiautc
ee06a
num06a
bp06
```

**Comment by helgee** [comment]
Thanks! Even more incentive for me to get AstroBase.jl ready for release. Most of these have already been ported to pure Julia.

**Comment by crbinz** [comment]
I'd be very interested in that.
