### ISSUE TITLE
Deprecate linear algebra functions

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/ERFA.jl#46]
Maintaining wrappers for basic linear algebra functions does not make sense. Use the approach from [SPICE.jl](https://github.com/JuliaAstro/SPICE.jl/blob/master/src/m.jl#L279): Deprecate the functions and point towards sensible pure-Julia alternatives.

* [x] [anp](https://github.com/liberfa/erfa/blob/master/src/anp.c) - Normalize angle into the range 0 <= a < 2pi.
* [X] ~[anpm](https://github.com/liberfa/erfa/blob/master/src/anpm.c) - Normalize angle into the range -pi <= a < +pi.~
* [x] [cp](https://github.com/liberfa/erfa/blob/master/src/cp.c) - Copy a p-vector.
* [x] [cpv](https://github.com/liberfa/erfa/blob/master/src/cpv.c) - Copy a position/velocity vector.
* [x] [cr](https://github.com/liberfa/erfa/blob/master/src/cr.c) - Copy an r-matrix.
* [x] [ir](https://github.com/liberfa/erfa/blob/master/src/ir.c) - Initialize an r-matrix to the identity matrix.
* [x] [p2pv](https://github.com/liberfa/erfa/blob/master/src/p2pv.c) - Extend a p-vector to a pv-vector by appending a zero velocity.
* [x] [pdp](https://github.com/liberfa/erfa/blob/master/src/pdp.c) - p-vector inner (=scalar=dot) product.
* [x] [pm](https://github.com/liberfa/erfa/blob/master/src/pm.c) - Modulus of p-vector.
* [x] [pmp](https://github.com/liberfa/erfa/blob/master/src/pmp.c) - P-vector subtraction.
* [x] [pn](https://github.com/liberfa/erfa/blob/master/src/pn.c) - Convert a p-vector into modulus and unit vector.
* [x] [ppp](https://github.com/liberfa/erfa/blob/master/src/ppp.c) - P-vector addition.
* [x] [ppsp](https://github.com/liberfa/erfa/blob/master/src/ppsp.c) - P-vector plus scaled p-vector.
* [x] [pv2p](https://github.com/liberfa/erfa/blob/master/src/pv2p.c) - Discard velocity component of a pv-vector.
* [x] ~[pvdpv](https://github.com/liberfa/erfa/blob/master/src/pvdpv.c) - Inner (=scalar=dot) product of two pv-vectors.~
* [x] [pvm](https://github.com/liberfa/erfa/blob/master/src/pvm.c) - Modulus of pv-vector.
* [x] [pvmpv](https://github.com/liberfa/erfa/blob/master/src/pvmpv.c) - Subtract one pv-vector from another.
* [x] [pvppv](https://github.com/liberfa/erfa/blob/master/src/pvppv.c) - Add one pv-vector to another.
* [X] ~[pvu](https://github.com/liberfa/erfa/blob/master/src/pvu.c) - Update a pv-vector.~
* [X] ~[pvup](https://github.com/liberfa/erfa/blob/master/src/pvup.c) - Update a pv-vector, discarding the velocity component.~
* [x] ~[pvxpv](https://github.com/liberfa/erfa/blob/master/src/pvxpv.c) - Outer (=vector=cross) product of two pv-vectors.~
* [x] [pxp](https://github.com/liberfa/erfa/blob/master/src/pxp.c) - p-vector outer (=vector=cross) product.
* [x] ~[rx](https://github.com/liberfa/erfa/blob/master/src/rx.c) - Rotate an r-matrix about the x-axis.~
* [x] [rxp](https://github.com/liberfa/erfa/blob/master/src/rxp.c) - Multiply a p-vector by an r-matrix.
* [x] [rxpv](https://github.com/liberfa/erfa/blob/master/src/rxpv.c) - Multiply a pv-vector by an r-matrix.
* [x] [rxr](https://github.com/liberfa/erfa/blob/master/src/rxr.c) - Multiply two r-matrices.
* [x] ~[ry](https://github.com/liberfa/erfa/blob/master/src/ry.c) - Rotate an r-matrix about the y-axis.~
* [x] ~[rz](https://github.com/liberfa/erfa/blob/master/src/rz.c) - Rotate an r-matrix about the z-axis.~
* [x] [s2xpv](https://github.com/liberfa/erfa/blob/master/src/s2xpv.c) - Multiply a pv-vector by two scalars.
* [x] [sxp](https://github.com/liberfa/erfa/blob/master/src/sxp.c) - Multiply a p-vector by a scalar.
* [x] [sxpv](https://github.com/liberfa/erfa/blob/master/src/sxpv.c) - Multiply a pv-vector by a scalar.
* [x] [tr](https://github.com/liberfa/erfa/blob/master/src/tr.c) - Transpose an r-matrix.
* [x] [trxp](https://github.com/liberfa/erfa/blob/master/src/trxp.c) - Multiply a p-vector by the transpose of an r-matrix.
* [x] [trxpv](https://github.com/liberfa/erfa/blob/master/src/trxpv.c) - Multiply a pv-vector by the transpose of an r-matrix.
* [x] [zp](https://github.com/liberfa/erfa/blob/master/src/zp.c) - Zero a p-vector.
* [x] [zpv](https://github.com/liberfa/erfa/blob/master/src/zpv.c) - Zero a pv-vector.
* [x] [zr](https://github.com/liberfa/erfa/blob/master/src/zr.c) - Initialize an r-matrix to the null matrix.

**Comment by david-macmahon** [comment]
I'm not sure which functions you are referring to specifically, so I don't know how applicable my comment will be, but I think it's important to maintain (or at least be able to maintain, if one so chooses) numerical consistency with other non-Julia ERFA code.  Alternatives that are mathematically equivalent may not produce numerically equivalent results.

**Comment by helgee** [comment]
This is the list of functions I would like to deprecate without checking in detail:

* [anp](https://github.com/liberfa/erfa/blob/master/src/anp.c) - Normalize angle into the range 0 <= a < 2pi.
* [anpm](https://github.com/liberfa/erfa/blob/master/src/anpm.c) - Normalize angle into the range -pi <= a < +pi.
* [cp](https://github.com/liberfa/erfa/blob/master/src/cp.c) - Copy a p-vector.
* [cpv](https://github.com/liberfa/erfa/blob/master/src/cpv.c) - Copy a position/velocity vector.
* [cr](https://github.com/liberfa/erfa/blob/master/src/cr.c) - Copy an r-matrix.
* [ir](https://github.com/liberfa/erfa/blob/master/src/ir.c) - Initialize an r-matrix to the identity matrix.
* [p2pv](https://github.com/liberfa/erfa/blob/master/src/p2pv.c) - Extend a p-vector to a pv-vector by appending a zero velocity.
* [pdp](https://github.com/liberfa/erfa/blob/master/src/pdp.c) - p-vector inner (=scalar=dot) product.
* [pm](https://github.com/liberfa/erfa/blob/master/src/pm.c) - Modulus of p-vector.
* [pmp](https://github.com/liberfa/erfa/blob/master/src/pmp.c) - P-vector subtraction.
* [pn](https://github.com/liberfa/erfa/blob/master/src/pn.c) - Convert a p-vector into modulus and unit vector.
* [ppp](https://github.com/liberfa/erfa/blob/master/src/ppp.c) - P-vector addition.
* [ppsp](https://github.com/liberfa/erfa/blob/master/src/ppsp.c) - P-vector plus scaled p-vector.
* [pv2p](https://github.com/liberfa/erfa/blob/master/src/pv2p.c) - Discard velocity component of a pv-vector.
* [pvdpv](https://github.com/liberfa/erfa/blob/master/src/pvdpv.c) - Inner (=scalar=dot) product of two pv-vectors.
* [pvm](https://github.com/liberfa/erfa/blob/master/src/pvm.c) - Modulus of pv-vector.
* [pvmpv](https://github.com/liberfa/erfa/blob/master/src/pvmpv.c) - Subtract one pv-vector from another.
* [pvppv](https://github.com/liberfa/erfa/blob/master/src/pvppv.c) - Add one pv-vector to another.
* [pvu](https://github.com/liberfa/erfa/blob/master/src/pvu.c) - Update a pv-vector.
* [pvup](https://github.com/liberfa/erfa/blob/master/src/pvup.c) - Update a pv-vector, discarding the velocity component.
* [pvxpv](https://github.com/liberfa/erfa/blob/master/src/pvxpv.c) - Outer (=vector=cross) product of two pv-vectors.
* [pxp](https://github.com/liberfa/erfa/blob/master/src/pxp.c) - p-vector outer (=vector=cross) product.
* [rx](https://github.com/liberfa/erfa/blob/master/src/rx.c) - Rotate an r-matrix about the x-axis.
* [rxp](https://github.com/liberfa/erfa/blob/master/src/rxp.c) - Multiply a p-vector by an r-matrix.
* [rxpv](https://github.com/liberfa/erfa/blob/master/src/rxpv.c) - Multiply a pv-vector by an r-matrix.
* [rxr](https://github.com/liberfa/erfa/blob/master/src/rxr.c) - Multiply two r-matrices.
* [ry](https://github.com/liberfa/erfa/blob/master/src/ry.c) - Rotate an r-matrix about the y-axis.
* [rz](https://github.com/liberfa/erfa/blob/master/src/rz.c) - Rotate an r-matrix about the z-axis.
* [s2xpv](https://github.com/liberfa/erfa/blob/master/src/s2xpv.c) - Multiply a pv-vector by two scalars.
* [sxp](https://github.com/liberfa/erfa/blob/master/src/sxp.c) - Multiply a p-vector by a scalar.
* [sxpv](https://github.com/liberfa/erfa/blob/master/src/sxpv.c) - Multiply a pv-vector by a scalar.
* [tr](https://github.com/liberfa/erfa/blob/master/src/tr.c) - Transpose an r-matrix.
* [trxp](https://github.com/liberfa/erfa/blob/master/src/trxp.c) - Multiply a p-vector by the transpose of an r-matrix.
* [trxpv](https://github.com/liberfa/erfa/blob/master/src/trxpv.c) - Multiply a pv-vector by the transpose of an r-matrix.
* [zp](https://github.com/liberfa/erfa/blob/master/src/zp.c) - Zero a p-vector.
* [zpv](https://github.com/liberfa/erfa/blob/master/src/zpv.c) - Zero a pv-vector.
* [zr](https://github.com/liberfa/erfa/blob/master/src/zr.c) - Initialize an r-matrix to the null matrix.

Anything that concerns you at first glance @david-macmahon?

**Comment by helgee** [comment]
Also, we would not remove the wrappers for these functions entirely but unexport them and mangle the names (e.g. `tr` -> `_tr`) to still have the ability to test that they are in fact equivalent to pure Julia replacements.

**Comment by david-macmahon** [comment]
That's quite a list and I agree that the functionality of many if not all of them could be accomplished using other Julia functionality with numerical equivalence.  I think it would be fine not to export them, but I would vote against mangling the names as it would make it harder to transcribe ERFA-related code to Julia.  What benefit would name mangling provide?  I'm not able to think of any, but maybe I'm missing something.

**Comment by helgee** [comment]
The name mangling is necessary to be able to throw deprecation warnings. You could still use the unmangled names in a script but would be warned if Julia is run with deprecation warnings enabled.
