### ISSUE TITLE
ERFA.jl 1.0

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/ERFA.jl#50]
ERFA.jl is now almost seven years old (first commit was on 2014-02-26) and deserves a stable 1.0 release. I want to complete the following tasks beforehand:

- [x] Resolve #46 
- [x] Update ERFA_jll to 1.7.2 (https://github.com/JuliaPackaging/Yggdrasil/pull/2606)
- [x] Re-discuss public API and exports
    - Right now we only export deprecated symbols which is weird.
- [x] Remove deprecations
- [x] General housekeeping (CI, documentation clean-ups, coverage, etc.)

Did I forget anything? Do we need another 0.7 release before 1.0?

**Comment by helgee** [comment]
@giordano IIRC you were in favor of unexporting all the things. Are you still? With https://github.com/JuliaLang/julia/issues/1255 solved it is not as problematic anymore, no?

**Comment by giordano** [comment]
Oops, I was going to reply yesterday, but got distracted and forgot to do it.  Yeah, I think it's fine to unexport symbols: it'd be a breaking change and it's a good idea to polish the API for v1.0

**Comment by david-macmahon** [comment]
> Do we need another 0.7 release before 1.0?

FWIW, I miss `ae2hd` etc so I'd be happy with a(nother?) 0.7 (or even another 0.6) release before 1.0.

**Comment by helgee** [comment]
I will tag 1.0 once #60 is merged 🎉

**Comment by helgee** [comment]
I have tagged ERFA 1.0 (Julia 1.3+, ERFA_jll 1.7+) and ERFA 1.1 (Julia 1.6+, ERFA_jll 2.0+)
