### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by helgee** [JuliaAstro/ERFA.jl#55]
I just realised that we have had a licensing problem for a while:

The docstrings are copied from ERFA and thus are covered by ERFA's modified BSD-license which is less permissive than ERFA.jl's MIT license and thus incompatible. I see two possibilities:

1. Change ERFA.jl license to MPLv2 or BSD
2. Add an exception for the docstrings to the license and keep the rest MIT

**Comment by helgee** [comment]
Alright, I propose an emoji vote:

1. Switch to MPLv2: 🎉 
2. Switch to BSD: 👀 
3. Add an exception for docstrings to license:  🚀 

CC'ing all contributors with copyrightable commits:

- [x] @helgee 
- [ ] @nirinA 
- [ ] @kbarbary 
- [ ] @nolta 
- [ ] @giordano 
- [ ] @crbinz

**Comment by crbinz** [comment]
I don't think I understand the options well enough to vote, so I'll abstain.

**Comment by helgee** [comment]
I have contacted `@kbarbary` and `@nirinA` via e-mail.

**Comment by nirinA** [comment]
i am fine with the option you may consider appropriate. i never discerned the differences between all those licenses.

**Comment by kbarbary** [comment]
I don't have a preference. Any of the proposed licenses are fine with me. Thanks for asking!

**Comment by helgee** [comment]
So....

I believe I jumped the gun on this one. Still IANAL but having read more about it, I have come to the conclusion that MIT and 3-clause BSD are in fact compatible (the old and out of favour 4-clause BSD is incompatible). Thus I would propose the following change instead: https://github.com/JuliaAstro/ERFA.jl/pull/58

**Comment by helgee** [comment]
If I do not hear any objections by tomorrow, I will merge #58 and close this. Sorry for the noise.
